version: '3.8'
services:
  gateway:
    build: gateway/.
    image: amazoncorretto:11-alpine-jdk
    container_name: shared-it-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
      - SHAREIT_SERVER_URL=http://localhost:9090

  server:
    build: server/.
    image: amazoncorretto:11-alpine-jdk
    container_name: shared-it-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6541/postgres

  db:
    image: postgres:13.7-alpine
    container_name: db-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres